### ISSUE TITLE
Compile dependency com.asciidocfx.pty4j:pty4j does not work anymore

### ISSUE THREAD

**Issue by pbi-qfs** [javaterminal/TerminalFX#5]
```
[ERROR] Failed to execute goal on project terminalfx: Could not resolve dependencies for project 
com.kodedu.asciidocfx:terminalfx:jar:1.4: Failed to collect dependencies at 
com.asciidocfx.pty4j:pty4j:jar:0.7.3: Failed to read artifact descriptor for 
com.asciidocfx.pty4j:pty4j:jar:0.7.3: Could not transfer artifact com.asciidocfx.pty4j:pty4j:pom:0.7.3 
from/to rahmanusta-releases (http://asciidocfx.com/build): Host name 'asciidocfx.com' does not 
match the certificate subject provided by the peer (CN=kodedu.com) -> [Help 1]
```

**Comment by rahmanusta** [comment]
It is in transition to new server. It will be updated soon.

**Comment by crra** [comment]
@rahmanusta: the issue is still present. Would you mind updating the source project https://github.com/asciidocfx/pty4j to the version 0.7.**3** so that the dependency could be resolved manually? The repo and the upstream repo still state 0.7.**2** as version number and it seams that there is no cache of this particular version available:

**Comment by rahmanusta** [comment]
Dependencies were moved to github. Details are in READMe.
