### ISSUE TITLE
Application not closing automatically when it contains a TerminalTab

### ISSUE THREAD

**Issue by Xerus2000** [javaterminal/TerminalFX#9]
```
import com.terminalfx.TerminalTab;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.TabPane;
import javafx.stage.Stage;

public class TestApplication extends Application {

	@Override
	public void start(Stage primaryStage) {
		TabPane tabPane = new TabPane();
		primaryStage.setScene(new Scene(tabPane));
		tabPane.getTabs().add(new TerminalTab());
		primaryStage.show();
	}
	
}
```

When running this simple Application, it keeps running in background even after closing the Stage. However, after commenting out the adding of the TerminalTab, it terminates as expected.

**Comment by rahmanusta** [comment]
Usage is not correct. Use it like that https://github.com/javaterminal/TerminalFX#3-usage

**Comment by sghpjuikit** [comment]
@rahmanusta you dismissed this issue prematurely

I can reproduce the reported issue always. Simply run `TerminalAppStarter.main()` after commenting out the code in `stop()` method like this:
```
    @Override
    public void stop() throws Exception {
//        Platform.exit();
//        System.exit(0);
    }
``` 

It is easy to understand what happens: this library uses non-daemon threads, which means JVM will not shut down until they shut down. This may or may not be a desired behavior, but it should be possible to specify this.

Otherwise developers are forced to use Platform.exit() and other hacks around the issue.

I can confirm the issue goes away once the threads constructed in `ThreadHelper` are daemon. Like:
```
    private static final ExecutorService singleExecutorService = Executors.newSingleThreadExecutor(r -> {
        Thread t = new Thread(r);
        t.setName("terminalFx");
        t.setDaemon(true); // fixes the issue
        return t;
    });
```

Changing this behavior at this point is not a good idea however, so proper patch would need to default to this behavior and provide settings to override the behavior.
